baseURL = 'https://homephonete.github.io/ella-tattari/'
defaultContentLanguage = 'en'
title = 'Ella Tattari'
theme = 'hugo-theme-stack'
locale                 = "en-us"
hasCJKLanguage         = false

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
