baseURL = 'https://homephonete.github.io/ella-tattari/'
defaultContentLanguage = 'en'
title = 'Ella Tattari'
theme = 'hugo-theme-stack'
locale                 = "en-us"
hasCJKLanguage         = false

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

