mainSections   = ["post"]
rssFullContent = true
favicon        = "img/IMG_0707.jpg"

[sidebar]
    avatar   = "img/IMG_0707.jpg"

[widgets]
    homepage = [
        { type = "search" },
    ]
    page     = [{ type = "toc" }]
